In [45]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
import numpy as np

In [34]:
X, y = make_moons(n_samples=1000, noise=0.05)

In [35]:
dbscan = DBSCAN(eps=0.05, min_samples=5)

In [36]:
dbscan.fit(X)

DBSCAN(eps=0.05)

#### Rotulos achados, ou melhor, percebidos

In [37]:
set(dbscan.labels_)

{-1, 0, 1, 2, 3, 4}

In [38]:
len(dbscan.core_sample_indices_)

809

#### Indices

In [39]:
dbscan.core_sample_indices_

array([  0,   3,   4,   5,   6,   7,   8,   9,  11,  12,  13,  15,  16,
        17,  18,  19,  20,  22,  23,  24,  25,  26,  27,  28,  29,  31,
        32,  33,  34,  35,  37,  38,  39,  40,  42,  44,  45,  46,  47,
        48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  59,  60,  62,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  76,  77,  78,  80,
        81,  82,  83,  84,  85,  87,  88,  89,  90,  91,  92,  94,  95,
        97,  98,  99, 100, 101, 102, 104, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 118, 120, 121, 123, 125, 126, 127, 128,
       130, 131, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 147,
       149, 150, 151, 152, 153, 154, 155, 156, 157, 159, 160, 161, 163,
       164, 165, 166, 167, 169, 171, 172, 173, 174, 175, 176, 177, 178,
       181, 182, 183, 184, 185, 187, 188, 189, 191, 193, 194, 195, 197,
       198, 199, 200, 202, 203, 205, 207, 208, 209, 210, 211, 212, 213,
       214, 215, 216, 217, 220, 221, 222, 224, 225, 226, 228, 23

In [40]:
dbscan.components_

array([[-0.74741434,  0.61090958],
       [ 0.33471006,  0.99651447],
       [-0.19392582,  0.89417253],
       ...,
       [-0.04279829,  0.34024554],
       [-0.13169272,  1.01470336],
       [ 1.00161816, -0.00288581]])

#### Components_ sao os valores X

In [41]:
X[0] == dbscan.components_[0]

array([ True,  True])

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)

In [46]:
X_new = np.array([[-0.5, 0], [0, 0.5], [1, -0.1], [2, 1]])

In [47]:
knn.predict(X_new)

array([0, 3, 1, 2], dtype=int64)

In [48]:
knn.predict_proba(X_new)

array([[0.76, 0.  , 0.  , 0.24, 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.7 , 0.3 , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  ]])